module.exports = {
    githubIds: [
        "alextsoi",
        "derone",
        "03win",
        "CarmenCCy",
        "E3cho",
        "Kapo11111",
        "Nata-w",
        "UnaLam",
        "WinnieLeung0724",
        "atintina",
        "atintina",
        "bern-cc",
        "changyungchunrenee",
        "chankitfu",
        "charlieccy",
        "chiho-sdad",
        "chongwl0861",
        "christyc1129",
        "ckizzi",
        "ckyyyyy",
        "cwk729",
        "dlalstjq22",
        "goodbyevictorialhy",
        "kittychan0720",
        "loboyu",
        "mathildayang",
        "ningkiu0926ss",
        "oilammk20",
        "sabinachanx",
        "stephytam",
        "tiffanyleungi",
        "youngbeen1002",
        "youngbeen1002",
        "yumicornnn",
        "Skylettwong",
        "chuntx"
    ],
    "githubPrefix": "https://github.com/",
    "githubSuffix": "/2019-polyu-sd3861-lecture2",
    "githubRawPrefix": "https://raw.githubusercontent.com/"
};